#ifndef DEFINES_INO
#define DEFINES_INO

// DIGITAL PINS
#define PWM_MOSFET_PIN  3
#define LOAD_MOSFET_PIN 5
//#define TEMP_SENSOR_PIN 9

// ANALOG PINS
#define GENERATOR_VOLTAGE_PIN A1
#define BATTERY_VOLTAGE_PIN   A2
#define GENERATOR_CURRENT_PIN A6
#define LOAD_CURRENT_PIN   A7

#endif
