// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IncrementLevelBTN = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_IncrementLevelBTN, 60);
    lv_obj_set_height(ui_IncrementLevelBTN, 60);
    lv_obj_set_x(ui_IncrementLevelBTN, 65);
    lv_obj_set_y(ui_IncrementLevelBTN, 100);
    lv_obj_set_align(ui_IncrementLevelBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IncrementLevelBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_IncrementLevelBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_IncrementLevelBTN, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IncrementLevelBTN, lv_color_hex(0x1D8F17), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IncrementLevelBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_IncrementLevelBTN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_IncrementLevelBTN, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_IncrementLevelBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_IncrementLevelBTN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IncrementLevelBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_IncrementLevelBTN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IncrementLevelBTN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IncrementLevelBTN, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IncrementLevelBTN, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IncrementSign = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_IncrementSign, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IncrementSign, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IncrementSign, 65);
    lv_obj_set_y(ui_IncrementSign, 100);
    lv_obj_set_align(ui_IncrementSign, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IncrementSign, "+");
    lv_obj_set_style_text_color(ui_IncrementSign, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IncrementSign, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IncrementSign, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IncrementLevelBTN1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_IncrementLevelBTN1, 60);
    lv_obj_set_height(ui_IncrementLevelBTN1, 60);
    lv_obj_set_x(ui_IncrementLevelBTN1, 169);
    lv_obj_set_y(ui_IncrementLevelBTN1, 100);
    lv_obj_set_align(ui_IncrementLevelBTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IncrementLevelBTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_IncrementLevelBTN1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_IncrementLevelBTN1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IncrementLevelBTN1, lv_color_hex(0xDF0404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IncrementLevelBTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_IncrementLevelBTN1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_IncrementLevelBTN1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_IncrementLevelBTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_IncrementLevelBTN1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IncrementLevelBTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_IncrementLevelBTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IncrementLevelBTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IncrementLevelBTN1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IncrementLevelBTN1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DecrementSign = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_DecrementSign, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DecrementSign, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DecrementSign, 169);
    lv_obj_set_y(ui_DecrementSign, 100);
    lv_obj_set_align(ui_DecrementSign, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DecrementSign, "-");
    lv_obj_set_style_text_font(ui_DecrementSign, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LEVELTITLE = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LEVELTITLE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LEVELTITLE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LEVELTITLE, 0);
    lv_obj_set_y(ui_LEVELTITLE, -91);
    lv_obj_set_align(ui_LEVELTITLE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LEVELTITLE, "LEVEL");
    lv_obj_set_style_text_color(ui_LEVELTITLE, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LEVELTITLE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LEVELTITLE, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LEVELVAL = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LEVELVAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LEVELVAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LEVELVAL, 0);
    lv_obj_set_y(ui_LEVELVAL, -30);
    lv_obj_set_align(ui_LEVELVAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LEVELVAL, "0");
    lv_obj_set_style_text_color(ui_LEVELVAL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LEVELVAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LEVELVAL, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);


}
