// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "UI/ui.h"
#include "UI/lv_conf.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_CaloriesLabel = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_CaloriesLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_CaloriesLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_CaloriesLabel, -119);
    lv_obj_set_y(ui_CaloriesLabel, -38);
    lv_obj_set_align(ui_CaloriesLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CaloriesLabel, "Calories");
    lv_obj_set_style_text_color(ui_CaloriesLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CaloriesLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CaloriesLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CaloriesUnit = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_CaloriesUnit, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_CaloriesUnit, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_CaloriesUnit, -60);
    lv_obj_set_y(ui_CaloriesUnit, -71);
    lv_obj_set_align(ui_CaloriesUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CaloriesUnit, "kcal");
    lv_obj_set_style_text_color(ui_CaloriesUnit, lv_color_hex(0xBD9A4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CaloriesUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CaloriesUnit, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CaloriesValue = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_CaloriesValue, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_CaloriesValue, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_CaloriesValue, -125);
    lv_obj_set_y(ui_CaloriesValue, -76);
    lv_obj_set_align(ui_CaloriesValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CaloriesValue, "50");
    lv_obj_set_style_text_color(ui_CaloriesValue, lv_color_hex(0xBD9A4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CaloriesValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CaloriesValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CadenceLabel = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_CadenceLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_CadenceLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_CadenceLabel, 120);
    lv_obj_set_y(ui_CadenceLabel, -38);
    lv_obj_set_align(ui_CadenceLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CadenceLabel, "Cadence");
    lv_obj_set_style_text_color(ui_CadenceLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CadenceLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CadenceLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CadenceValue = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_CadenceValue, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_CadenceValue, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_CadenceValue, 119);
    lv_obj_set_y(ui_CadenceValue, -76);
    lv_obj_set_align(ui_CadenceValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CadenceValue, "50");
    lv_obj_set_style_text_color(ui_CadenceValue, lv_color_hex(0xB04DCE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CadenceValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CadenceValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CadenceUnit = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_CadenceUnit, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_CadenceUnit, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_CadenceUnit, 184);
    lv_obj_set_y(ui_CadenceUnit, -71);
    lv_obj_set_align(ui_CadenceUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CadenceUnit, "rpm");
    lv_obj_set_style_text_color(ui_CadenceUnit, lv_color_hex(0xB04DCE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CadenceUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CadenceUnit, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedLabel = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_SpeedLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SpeedLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SpeedLabel, -124);
    lv_obj_set_y(ui_SpeedLabel, 104);
    lv_obj_set_align(ui_SpeedLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedLabel, "Speed");
    lv_obj_set_style_text_color(ui_SpeedLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedUnit = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_SpeedUnit, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SpeedUnit, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SpeedUnit, -40);
    lv_obj_set_y(ui_SpeedUnit, 71);
    lv_obj_set_align(ui_SpeedUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedUnit, "km/h");
    lv_obj_set_style_text_color(ui_SpeedUnit, lv_color_hex(0x31C7D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedUnit, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedValue = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_SpeedValue, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SpeedValue, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SpeedValue, -122);
    lv_obj_set_y(ui_SpeedValue, 67);
    lv_obj_set_align(ui_SpeedValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedValue, "20.0");
    lv_obj_set_style_text_color(ui_SpeedValue, lv_color_hex(0x31C7D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedValue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DistanceLabel = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_DistanceLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_DistanceLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_DistanceLabel, 125);
    lv_obj_set_y(ui_DistanceLabel, 107);
    lv_obj_set_align(ui_DistanceLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DistanceLabel, "Distance");
    lv_obj_set_style_text_color(ui_DistanceLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DistanceLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DistanceLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DistanceUnit = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_DistanceUnit, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_DistanceUnit, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_DistanceUnit, 192);
    lv_obj_set_y(ui_DistanceUnit, 71);
    lv_obj_set_align(ui_DistanceUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DistanceUnit, "km");
    lv_obj_set_style_text_color(ui_DistanceUnit, lv_color_hex(0x2EAE72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DistanceUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DistanceUnit, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedValue1 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_SpeedValue1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SpeedValue1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SpeedValue1, 123);
    lv_obj_set_y(ui_SpeedValue1, 68);
    lv_obj_set_align(ui_SpeedValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedValue1, "20.0");
    lv_obj_set_style_text_color(ui_SpeedValue1, lv_color_hex(0x2EAE72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedValue1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *btnMusic = lv_btn_create(ui_Screen3); // Replace with your actual screen
    lv_obj_set_size(btnMusic, 40, 35);
    lv_obj_set_pos(btnMusic, 430, 285); // Same position as btnNext

    lv_obj_t *iconMusic = lv_label_create(btnMusic);
    lv_label_set_text(iconMusic, LV_SYMBOL_AUDIO); // Music-like icon
    lv_obj_center(iconMusic);
}
