// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "UI/ui_helpers.h"
#include "UI/ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_CurrentArc;
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_IncrementLevelBTN;
extern lv_obj_t * ui_LEVELTITLE;
extern lv_obj_t * ui_LEVELVAL;
extern lv_obj_t * ui_IncrementSign;
extern lv_obj_t * ui_IncrementLevelBTN1;
extern lv_obj_t * ui_DecrementSign;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_CaloriesLabel;
extern lv_obj_t * ui_CaloriesUnit;
extern lv_obj_t * ui_CaloriesValue;
extern lv_obj_t * ui_CadenceLabel;
extern lv_obj_t * ui_CadenceValue;
extern lv_obj_t * ui_CadenceUnit;
extern lv_obj_t * ui_SpeedLabel;
extern lv_obj_t * ui_SpeedUnit;
extern lv_obj_t * ui_SpeedValue;
extern lv_obj_t * ui_DistanceLabel;
extern lv_obj_t * ui_DistanceUnit;
extern lv_obj_t * ui_SpeedValue1;

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_PlotTitle;
extern lv_obj_t * ui_XLabel;
extern lv_obj_t * ui_YLabel;
extern lv_obj_t * ui_YLabel1;

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
// extern lv_obj_t * ui_Image1;
// extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_CooldownMessage;
extern lv_obj_t * ui_SafeProceedMessage;
extern lv_obj_t * ui_Label7;

// CUSTOM VARIABLES

extern lv_obj_t * ui_BikePic;
extern lv_obj_t * batteryGroup;

// LV_IMG_DECLARE(ui_img_bikeicon_png);    // assets/BikeIcon.png
// LV_IMG_DECLARE(ui_img_batterypic_png);    // assets/BatteryPic.png

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif